name: Vodary Paris — World literatures in original
url: https://vodary.paris.fr
description: across languages and scripts

permalink: /book/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
