name: Éditions Vodary, Paris
url: https://vodary.paris.fr
description: **Éditions Vodary** is an open-access publisher in Paris. It publishes literary works from all over the world, in their diverse languages and scripts.

permalink: /book/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
